-- 1. ATUALIZAÇÃO DAS TAXAS GLOBAIS (CONFORME FOTO)
UPDATE public.admin_config SET dollar_rate = 5.7, tax_importer = 25, tax_admin = 20, tax_nf = 3 WHERE id = 'global';

-- 2. IMPORTAÇÃO DOS PRODUTOS (FILTRADO: SEM AIRGUN/CARABINA)
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('AMOEBA AEG M4 AM-014 CARBINE AIRSOFT RIFLE BLACK', 'AMOEBA', 249, 'https://www.arsenalsports.com/img/8345/produtos/600/9a84e8094d204d5841d57a8f7f90c6e6.png', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'AEG', 'O fuzil de asHop Up AM-014 emprega um novo design de foregrip para adaptar o método de tiro de rifle moderno, bem como sistema de trilho modular leve que permite uma ampla gama de acessórios opcionais, como luzes e lasers. O sistema de controle de disparo eletrônico de 3ª geração melhorado (EFCS) pode resistir a uma corrente de disparo de 30A e fornecer uma melhor posição do ciclo do pistão, o que garante uma velocidade de queima mais estável e prolonga a longevidade da mola.', 'https://www.arsenalsports.com/produto/-amoeba-aeg-m4-am014-carbine-airsoft-rifle-black-8345.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('AMOEBA SILENCER 235MM QUICK DETACH 14MM CW LONG FOR MSR BLACK', 'AMOEBA', 35, 'https://www.arsenalsports.com/img/7770/produtos/600/bc19df05e44a443ce7465b6d68053347.jpg', (SELECT id FROM public.categories WHERE slug = 'snipers'), 'AEG', 'Diametro: 38mm
Se encaixa no cano com flashhiders direto ( Quick detach mechanism that fit direct with flash hider )
Marcações gravadas
Toda a construção metálica
Especifico para Sniper FH-MSR-01
Comprimento: 235mm
Peso: 250g

Nota:
Este é um supressor falso, e não-funciona
Não usar em armas reais, pois pode explodir
Use somente em airsoft, não vai diminuir o som.', 'https://www.arsenalsports.com/produto/amoeba-silencer-235mm-quick-detach-14mm-cw-long-for-msr-black-7770.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('AMOEBA AEG M4 MUTANT AMM13 AIRSOFT RIFLE BLACK', 'AMOEBA', 219, 'https://www.arsenalsports.com/img/17958/produtos/600/33bf82b4dc3e67a2ac834ff636f97f32.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'AEG', 'Tipo AEG. GearBox EFCS. Material de fibra de nylon, alumínio, metal. Tipo de Disparo: Fire Mode Totalmente Automático / Semi Auto / Seguro. Material da GearBox liga de zine fundido. Hop-Up ajustável. Magazine: 140 Rounds. Liberação Rápida de Mola. Tipos de bateria: 7,4v - 11,1v. Peso 2620g. Comprimento 820-900mm. VEM COM 01 MAGAZINE 140 ROUNDS MID-CAP.', 'https://www.arsenalsports.com/produto/-amoeba-aeg-m4-mutant-amm13-airsoft-rifle-black-17958.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('AMOEBA AEG M4 MUTANT AMM7 AIRSOFT RIFLE BLACK', 'AMOEBA', 219, 'https://www.arsenalsports.com/img/17954/produtos/600/c2c3e0661b01beb9084a31e86f48217e.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'AEG', 'Série AMOEBA M4 redesenhada. Receptor superior e inferior robusto e leve em polímero. Guarda-mão M-LOK de liberação rápida em alumínio CNC. Comprimentos de cano e guarda-mão altamente configuráveis. Conjunto completo de cano externo, cano interno e hop-up de encaixe direto. 

**Especificações:**
- ARES Amoeba EFCS.
- GearBox EFCS
- Material de fibra de nylon, alumínio, metal
- Tipo de Disparo: Fire Mode Totalmente Automático / Semi Auto / Seguro (O Fire Mode pode ser personalizado pelo Programador de GearBox Eletrônica)
- Material da GearBox liga de zine fundido
- Hop-Up ajustável
- Capacidade do Magazine: 140 Rounds
- Tipos de bateria: 7,4v - 11,1v
- Conector da Bateria: DEANS
- Peso 2360gg
- Comprimento 565-660mm
- **VEM COM 01 MAGAZINE 140 ROUNDS MID-CAP**', 'https://www.arsenalsports.com/produto/-amoeba-aeg-m4-mutant-amm7-airsoft-rifle-black-17954.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('SEEKINS PRECISION EMG G&G AEG TGR SBR8 12" RAIL AIRSOFT RIFLE GREY', 'SEEKINS PRECISION', 390, 'https://www.arsenalsports.com/img/23378/produtos/600/cb32bf2a97c2bf4f492db1d314d95696.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'AEG', 'Material: Polímero / Metal / Alumínio, Motor: Long Type 18K, Rolamentos da GearBox com esferas de 8 mm, Comprimento interno do cano 343mm, Magazine Capacidade: 90 Rounds, Comprimento Total: 725mm, Peso 2825g, Gatilho Eletrônico Sim, MOSFET Sim, Hop-Up: Ajustável, Modo de Disparo: Safe, Semi-Auto, Full-Auto.', 'https://www.arsenalsports.com/produto/-seekins-precision-emg-gg-aeg-tgr-sbr8-12-rail-airsoft-rifle-grey-23378.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('TARAN TACTICAL JAG PRECISION ARMY ARMAMENT GBB HI-CAPA JW4 TTI ALPHA COMBAT MASTER BLOWBACK AIRSOFT PISTOL DUAL TONE', 'TARAN TACTICAL', 169, 'https://www.arsenalsports.com/img/25444/produtos/600/6558418d47a3f74fe657b56c14dae2d7.png', (SELECT id FROM public.categories WHERE slug = 'pistolas'), 'GBB', 'Slide com design RMR Optic Cut (usando a nova versão Small Enhanced Charging Muzzle).
Sistema de Blowback de Gás
Magazine Ling Dounle Stack Silver
"Ambi Thumb Safety" (liga/desliga a segurança sem alterar a aderência).
Tactical Magwell
Punho Hi-capa pontilhado à mão personalizado
Válvulas seladas de entrada e saída do magazine de nova geração
Capacidade do Magazine: Até 45 Rounds Long Magazine
Comprimento total: 250 mm
Peso: 1105 g
Blowback de Gás
Modo de Disparo: Safe, Semi-Auto
Hop-Up: Ajustável
Potência de Até 270 FPS', 'https://www.arsenalsports.com/produto/-taran-tactical-jag-precision-army-armament-gbb-hicapa-jw4-tti-alpha-combat-master-blowback-airsoft-pistol-dual-tone-25444.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('TARAN TACTICAL EMG STI ARMORER WORKS GBB HI-CAPA 2011 DVC 3-GUN BLOWBACK AIRSOFT PISTOL BLACK', 'TARAN TACTICAL', 155, 'https://www.arsenalsports.com/img/15482/produtos/600/3d9c4944e9a09cf18583b262aabaeae5.png', (SELECT id FROM public.categories WHERE slug = 'pistolas'), 'GBB', 'O STI DVC 3-GUN foi projetado especificamente para atender às necessidades dos entusiastas atuais de 3 canhões, mantendo-se fiel à herança de precisão, potência e velocidade da Diligenta, Vis, Celeritas. Atire mais suavemente. Dispare mais tempo entre as recargas. Considere o desempenho parte crítica da arma do seu arsenal de 3 pistolas devidamente coberta.', 'https://www.arsenalsports.com/produto/-taran-tactical-emg-sti-armorer-works-gbb-hicapa-2011-dvc-3gun-blowback-airsoft-pistol-black-15482.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('TARAN TACTICAL JAG PRECISION ARMY ARMAMENT GBB HI-CAPA JW4 TTI PIT VIPER CNC BLOWBACK AIRSOFT PISTOL BLACK', 'TARAN TACTICAL', 156, 'https://www.arsenalsports.com/img/25445/produtos/600/9f9c6cdf3256650b0e6444ea61c98585.png', (SELECT id FROM public.categories WHERE slug = 'pistolas'), 'GBB', 'A Army Armament John Wick 4 Taran Tactical Pit Viper é uma pistola de airsoft totalmente licenciada inspirada na arma de fogo usada no filme "John Wick". Ele oferece uma experiência de disparo autêntica e foi projetado tendo em mente a velocidade e o tiro competitivo. As superfícies de controle ampliadas garantem acesso rápido e fácil, e os dispositivos de segurança ambidestros aumentam a versatilidade da pistola.', 'https://www.arsenalsports.com/produto/-taran-tactical-jag-precision-army-armament-gbb-hicapa-jw4-tti-pit-viper-cnc-blowback-airsoft-pistol-black-25445.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('TARAN TACTICAL JAG PRECISION ARMY ARMAMENT GBB HI-CAPA JW4 TTI PIT VIPER STANDARD BLOWBACK AIRSOFT PISTOL BLACK', 'TARAN TACTICAL', 129, 'https://www.arsenalsports.com/img/25446/produtos/600/05283d78a7f936cf227747109b697bdc.png', (SELECT id FROM public.categories WHERE slug = 'pistolas'), 'GBB', 'A Army Armament John Wick 4 Taran Tactical Pit Viper é uma pistola de airsoft totalmente licenciada inspirada na arma de fogo usada no filme ''John Wick''. Ele oferece uma experiência de disparo autêntica e foi projetado tendo em mente a velocidade e o tiro competitivo. As superfícies de controle ampliadas garantem acesso rápido e fácil, e os dispositivos de segurança ambidestros aumentam a versatilidade da pistola. Uma característica marcante desta pistola é sua excelente ergonomia e manuseio, começando pelo pontilhado de alta qualidade no punho. O Pit Viper também possui uma placa RMR, permitindo aos usuários montar sua ótica preferida na pistola, e o ferrolho é construído em metal, garantindo durabilidade e acabamento de alta qualidade.', 'https://www.arsenalsports.com/produto/-taran-tactical-jag-precision-army-armament-gbb-hicapa-jw4-tti-pit-viper-standard-blowback-airsoft-pistol-black-25446.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('A&K AEG MASADA LONG ACR ADAPTIVE COMBAT AIRSOFT RIFLE BLACK', 'A&K', 269, 'https://www.arsenalsports.com/img/27410/produtos/600/f99569bdcfbc6834f91fe50e90e3d5bc.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'AEG', 'Receptor inferior de polímero de alta resistência. Receptor superior de liga de metal. Conjunto de cano totalmente metálico com HandGuard RIS estilo ACR totalmente metálico. Coronha retrátil/dobrável multiposição com suporte de bochecha ajustável. Controle de tiro ambidestro. Trilho superior de 20 mm de comprimento total com miras pretas dianteiras e traseiras. O batente de ferrolho simulado funcional permite fácil ajuste de hop up.', 'https://www.arsenalsports.com/produto/ak-aeg-masada-long-acr-adaptive-combat-airsoft-rifle-black-27410.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('TARAN TACTICAL JAG PRECISION ARMY ARMAMENT GBB HI-CAPA JW4 TTI SAND VIPER CNC BLOWBACK AIRSOFT PISTOL BRONZE', 'TARAN TACTICAL', 166, 'https://www.arsenalsports.com/img/25448/produtos/600/d04d645fb3b40e7316b6375c51a99306.png', (SELECT id FROM public.categories WHERE slug = 'pistolas'), 'GBB', 'A Army Armament John Wick 4 Taran Tactical Sand Viper é uma pistola de airsoft totalmente licenciada inspirada na arma de fogo usada no filme ''John Wick 4''. Ele oferece uma experiência de disparo autêntica e foi projetado tendo em mente a velocidade e o tiro competitivo. As superfícies de controle ampliadas garantem acesso rápido e fácil, e os dispositivos de segurança ambidestros aumentam a versatilidade da pistola. Uma característica marcante desta pistola é sua excelente ergonomia e manuseio, começando pelo pontilhado de alta qualidade no punho. O Sand Viper também possui uma placa RMR, permitindo aos usuários montar sua ótica preferida na pistola. O ferrolho da pistola é construído em alumínio CNC, garantindo durabilidade e acabamento de alta qualidade.', 'https://www.arsenalsports.com/produto/-taran-tactical-jag-precision-army-armament-gbb-hicapa-jw4-tti-sand-viper-cnc-blowback-airsoft-pistol-bronze-25448.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('A&K AEG MASADA LONG CARBINE ADAPTIVE COMBAT AIRSOFT RIFLE BLACK', 'A&K', 269, 'https://www.arsenalsports.com/img/27407/produtos/600/ed37b8d4a8b26c553c45f33f7d8ec9bb.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'AEG', 'Receptor superior de metal, receptor inferior de polímero de alto impacto. Estoque retrátil e dobrável de múltiplas posições. Miras dianteiras e traseiras rebatíveis (a mira traseira é removível). Receptor Full Railed Flat Top Upper para acessórios ópticos. Descanso de bochecha ajustável. Liberação magnética ambidestra, liberação de parafuso e chave seletora. Pontos de fixação QD Sling Swivel integrados (QD Sling Swivel não incluído).', 'https://www.arsenalsports.com/produto/ak-aeg-masada-long-carbine-adaptive-combat-airsoft-rifle-black-27407.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('A&K AEG MASADA LONG DMR ADAPTIVE COMBAT AIRSOFT RIFLE BLACK', 'A&K', 269, 'https://www.arsenalsports.com/img/27419/produtos/600/1d20d354482e576f714fc071de99785f.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'AEG', 'Receptor inferior de polímero de alta resistência. Receptor superior de liga de metal. Conjunto de cano totalmente de metal. Sistema de cano QD. HandGuard DMR estendido e coronha de rifle de precisão. Elevador de bochecha ajustável e almofada de coronha. Chave seletora ambidestra, liberação do carregador e liberação do ferrolho. Miras de backup dianteiras e traseiras dobráveis. Comprimento: 980mm / 1005mm. Peso total: 3280g. Material: Metal, Polímero de Alto Impacto. Comprimento do cano interno: 400 mm. Capacidade do Magazine: 300 Rounds Hi-Cap. Compatível com magazines da série M4/M16. Motor: Long Type. GearBox: Ver. 2 com 7mm. Totalmente atualizável, compatível com Tokyo Marui. Bateria: 9,6v 1600mAh. Hop-up: Sim, Ajustável. Modo de disparo: Safe, Semi-Auto, Full-Auto.', 'https://www.arsenalsports.com/produto/ak-aeg-masada-long-dmr-adaptive-combat-airsoft-rifle-black-27419.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('A&K AEG MASADA SHORT CQB ADAPTIVE COMBAT AIRSOFT RIFLE BLACK', 'A&K', 269, 'https://www.arsenalsports.com/img/27420/produtos/600/595f7276ef3290f721dd95f6d51b96d9.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'AEG', '- Receptor inferior de polímero de alta resistência
- Receptor superior de liga de metal
- Conjunto de cano CQB totalmente metálico
- HandGuard com trilho de comprimento CQB de metal
- Coronha retrátil/dobrável multiposição com suporte de bochecha ajustável
- Chave seletora ambidestra, liberação do carregador e liberação do ferrolho
- Miras de backup dianteiras e traseiras dobráveis ??com trilho superior de comprimento total para ótica
- Parada de ferrolho simulada funcional para ajuste fácil do hopup

**Especificações**:
- Comprimento: 540mm / 710mm-785mm
- Peso total: 3800g
- Material: Metal, Polímero de Alto Impacto
- Comprimento do cano interno: 400 mm
- Capacidade do Magazine: 300 Rounds Hi-Cap. Compatível com magazines da série M4/M16
- Motor: Long Type
- GearBox: Ver. 2 com 7mm. Totalmente atualizável, compatível com Tokyo Marui
- Bateria: 9,6v 1600mAh
- Hop-up: Sim, Ajustável
- Modo de disparo: Safe, Semi-Auto, Full-Auto', 'https://www.arsenalsports.com/produto/ak-aeg-masada-short-cqb-adaptive-combat-airsoft-rifle-black-27420.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('A&K AEG SR25K DMR FULL METAL AIRSOFT RIFLE BLACK', 'A&K', 266, 'https://www.arsenalsports.com/img/27391/produtos/600/ce5542d628f5c545da619326b3927662.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'AEG', 'Receptor totalmente em metal
- Frente RIS para acessórios táticos, trilho superior de comprimento total para ótica
- Coronha retrátil de guindaste
- Mira frontal e traseira flip-up
- Empunhadura dianteira incluída
- GearBox totalmente em metal com peças internas reforçadas
- Modos de disparo selecionáveis: Semi-Automático e Totalmente Automático

**Especificações:**
- Comprimento: 840mm - 920mm
- Peso: 3280g
- Potência de até 420 FPS
- Comprimento do Cano Interno: 363mm
- Capacidade do Magazine: 470 Rounds Hi-Cap. Funciona com magazines Airsoft AEG da série SR25
- GearBox: Ver. 2 Extended
- Motor: Long Type
- Modos de Disparo: Safe, Semi-Auto, Full-Auto
- Bateria: 9,6V Recomendada (Conector Small Tamiya)
- Hopup: Sim, Ajustável.', 'https://www.arsenalsports.com/produto/ak-aeg-sr25k-dmr-full-metal-airsoft-rifle-black-27391.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('A&K GBBR M1873 Winchester Lever Action Medium Type with M-Lock Rail Airsoft Rifle Wood & Gold', 'A&K', 233, 'https://www.arsenalsports.com/img/30538/produtos/600/c4e670fe3b18997ae2648a020566c11b.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'GBB', 'Coronha de madeira real com receptor de metal e conjunto de cano. O RIS picatinny superior permite a fixação de óticas, lasers e outros acessórios. Os slots M-LOK ao redor do HandGuard oferecem bastante espaço para empunhaduras, luzes e quaisquer outros acessórios compatíveis com M-LOK que você desejar! Peças internas de metal/sistema de gás, cano construído em metal e alça de alavanca D. Almofada de coronha de latão de alta qualidade. Anel de cordão integrado para transporte seguro. Alça de alavanca ampliada para uso fácil com luvas.', 'https://www.arsenalsports.com/produto/ak-gbbr-m1873-winchester-lever-action-medium-type-with-mlock-rail--airsoft-rifle-wood--gold-30538.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('A&K GBBR M1873 WINCHESTER LEVER ACTION MEDIUM TYPE WITH M-LOCK RAIL AIRSOFT RIFLE WOOD & BLACK', 'A&K', 0, 'https://www.arsenalsports.com/img/30537/produtos/600/8675d51efa3cad319896f8ee41303673.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'GBB', 'Coronha de madeira real com receptor de metal e conjunto de cano. O RIS picatinny superior permite a fixação de óticas, lasers e outros acessórios. Os slots M-LOK ao redor do HandGuard oferecem bastante espaço para empunhaduras, luzes e quaisquer outros acessórios compatíveis com M-LOK que você desejar! Peças internas de metal/sistema de gás, cano construído em metal e alça de alavanca D. Almofada de coronha de latão de alta qualidade. Anel de cordão integrado para transporte seguro. Alça de alavanca ampliada para uso fácil com luvas.', 'https://www.arsenalsports.com/produto/ak-gbbr-m1873-winchester-lever-action-medium-type-with-mlock-rail-airsoft-rifle-wood--black-30537.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('A&K GBBR M1873 Winchester Lever Action Medium Type with M-Lock Rail Airsoft Rifle Wood & Silver', 'A&K', 233, 'https://www.arsenalsports.com/img/30539/produtos/600/dc29b3626e7ebc343a5cb4e4ed4276a0.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'GBB', 'Coronha de madeira real com receptor de metal e conjunto de cano. O RIS picatinny superior permite a fixação de óticas, lasers e outros acessórios. Os slots M-LOK ao redor do HandGuard oferecem bastante espaço para empunhaduras, luzes e quaisquer outros acessórios compatíveis com M-LOK que você desejar! Peças internas de metal/sistema de gás, cano construído em metal e alça de alavanca D. Almofada de coronha de latão de alta qualidade. Anel de cordão integrado para transporte seguro. Alça de alavanca ampliada para uso fácil com luvas.', 'https://www.arsenalsports.com/produto/ak-gbbr-m1873-winchester-lever-action-medium-type-with-mlock-rail-airsoft-rifle-wood--silver-30539.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('A&K GBBR M1873 Winchester Lever Action Short Type Airsoft Rifle Wood & Gold', 'A&K', 185, 'https://www.arsenalsports.com/img/30535/produtos/600/cda8adcb4086ac5d7c2f5923073cdb73.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'GBB', 'Coronha de madeira real com receptor de metal e conjunto de cano. Peças internas de metal/sistema de gás, cano construído em metal e alça de alavanca D. Sistema de hopup ajustável. Almofada de coronha de latão. Anel de cordão integrado. Alça de alavanca ampliada. Carregador interno de 25 Rounds. Câmara de gás integrada no cano inferior.', 'https://www.arsenalsports.com/produto/ak-gbbr-m1873-winchester-lever-action-short-type-airsoft-rifle-wood--gold-30535.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('A&K GBBR M1873 WINCHESTER LEVER ACTION SHORT TYPE AIRSOFT RIFLE WOOD & BLACK', 'A&K', 0, 'https://www.arsenalsports.com/img/30532/produtos/600/6471bd56d9993e43463e4528e73311e9.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'GBB', '- Coronha de madeira real com receptor de metal e conjunto de cano
- Peças internas de metal/sistema de gás, cano construído em metal e alça de alavanca D
- Sistema de hopup ajustável
- Almofada de coronha de latão
- Anel de cordão integrado
- Alça de alavanca ampliada
- Carregador interno de 25 Rounds
- Câmara de gás integrada no cano inferior

**Especificações:**

- Potência de até 390FPS
- Comprimento: 630 mm
- Peso: 1690 g
- Sistema: Gás SEM Blowback
- Tipo de gás: Green Gas
- Modos de disparo: Tiro único, Ação de alavanca
- Capacidade do Magazine: 25 Rounds
- Hopup: Sim, Ajustável.', 'https://www.arsenalsports.com/produto/ak-gbbr-m1873-winchester-lever-action-short-type-airsoft-rifle-wood--black-30532.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('A&K GBBR M1873 Winchester Lever Action Short Type Airsoft Rifle Wood & Silver', 'A&K', 0, 'https://www.arsenalsports.com/img/30536/produtos/600/fd2839810c31c79d767889d9c40985c7.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'GBB', 'Este produto está indisponível no momento. Avisaremos você por e-mail se você preencher seus dados abaixo.', 'https://www.arsenalsports.com/produto/ak-gbbr-m1873-winchester-lever-action-short-type-airsoft-rifle-wood--silver-30536.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('A&K GBBR M1873 Winchester Lever Action Short Type with M-Lock Rail Airsoft Rifle Wood & Black', 'A&K', 213, 'https://www.arsenalsports.com/img/30540/produtos/600/535507c186543952096e9f3c5ee2fce6.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'GBB', 'Crown made of solid wood with a metal receiver and forend assembly. Top Picatinny RIS mount allows for mounting optical sights, lasers, and other accessories. M-LOK slots around the HandGuard provide ample space for grips, flashlights, and other M-LOK compatible accessories you desire. Internal components/gas system in metal, metal tube and retention lever. Integrated safety ring for secure transport. Extended retention lever for ease of use with glasses. Internal capacity for up to 25 Rounds and integrated Gas Chamber in the body of the Rifle.', 'https://www.arsenalsports.com/produto/ak-gbbr-m1873-winchester-lever-action-short-type-with-mlock-rail-airsoft-rifle-wood--black-30540.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('A&K GBBR M1873 Winchester Lever Action Short Type with M-Lock Rail Airsoft Rifle Wood & Silver', 'A&K', 213, 'https://www.arsenalsports.com/img/30542/produtos/600/d793503d2d6a705cab6e3bc703ccf84a.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'GBB', 'Wooden stock with metal receiver and barrel assembly. The top Picatinny RIS allows the attachment of optics, lasers, and other accessories. M-LOK slots around the HandGuard offer plenty of space for grips, lights, and other compatible M-LOK accessories you desire!', 'https://www.arsenalsports.com/produto/ak-gbbr-m1873-winchester-lever-action-short-type-with-mlock-rail-airsoft-rifle-wood--silver-30542.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('A&K GBBR M1873 Winchester Lever Action Short Type with M-LOCK Rail Airsoft Rifle Wood & Gold', 'A&K', 213, 'https://www.arsenalsports.com/img/30541/produtos/600/e0012693ae468e94560bbaf5e3e4b1df.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'GBB', 'Coronha de madeira real com receptor de metal e conjunto de cano. O RIS picatinny superior permite a fixação de óticas, lasers e outros acessórios. Os slots M-LOK ao redor do HandGuard oferecem bastante espaço para empunhaduras, luzes e quaisquer outros acessórios compatíveis com M-LOK que você desejar! Peças internas de metal/sistema de gás, cano construído em metal e alça de alavanca D. Almofada de coronha de latão de alta qualidade. Anel de cordão integrado para transporte seguro. Alça de alavanca ampliada para uso fácil com luvas.', 'https://www.arsenalsports.com/produto/ak-gbbr-m1873-winchester-lever-action-short-type-with-mlock-rail-airsoft-rifle-wood--gold-30541.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('A&K GBBR M1892 Winchester Lever Action Long Type with M-Lock Rail Airsoft Rifle Real Wood & Black', 'A&K', 239, 'https://www.arsenalsports.com/img/27522/produtos/600/af5c2548bea100ba2cff3a9f5b4469b8.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'GBB', '- Conjunto de receptor e barril de metal com estoque de madeira real
- Top picatinny RIS permite a fixação de ópticas, lasers e outros acessórios
- Os slots M-LOK ao redor do HandGuard oferecem bastante espaço para punhos, luzes e quaisquer outros acessórios compatíveis com M-LOK que você desejar!
- Peças metálicas internas/do sistema de gás, cano construído em metal e alça de alavanca D
- Almofada de latão de alta qualidade
- Anel de cordão integrado para transporte seguro
- Alça de alavanca ampliada para fácil utilização com luvas
- **Especificações:**
    - Comprimento: 950 mm
    - Peso: 2580g
    - Sistema: Green Gas
    - Modos de Disparo: Safe, Semi-Auto
    - Capacidade do Magazine: 25 Rounds
    - Hop-Up: Sim, Ajustável
    - Feito em Polímero e Metal', 'https://www.arsenalsports.com/produto/ak-gbbr-m1892-winchester-lever-action-long-type-with-mlock-rail-airsoft-rifle-real-wood--black-27522.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('A&K SPRING SVD DRAGUNOV WITH METAL GEARBOX AND REAL WOOD SNIPER AIRSOFT RIFLE', 'A&K', 0, 'https://www.arsenalsports.com/img/27536/produtos/600/a90de6742b02f8ccaefab37fbe010e93.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'Spring', '- Construção totalmente metálica. Barril totalmente em metal, receptor e tudo mais que deveria ser de metal
- HandGuard e estoque de madeira real
- Protetor de bochecha de atirador ajustável
- Visão traseira ajustável
- Hop-Up Ajustável
- Compartimento de bateria realista e discreto, pode precisar de assistência de ferramenta para abrir o compartimento da bateria
- Cobertura contra poeira tratada com fosfato

**Especificações:**
- Potência de até 420 FPS
- Comprimento: 1219mm
- Peso: 3500g
- Capacidade do Magazine: 180 rodadas - Mid-Cap
- Motor: Short Type
- Hop-Up: Sim, Ajustável', 'https://www.arsenalsports.com/produto/ak-spring-svd-dragunov-with-metal-gearbox-and-real-wood-sniper-airsoft-rifle-27536.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('A&K SPRING SVD DRAGUNOV WITH METAL GEARBOX AND WOOD SNIPER AIRSOFT RIFLE', 'A&K', 195, 'https://www.arsenalsports.com/img/27550/produtos/600/8c2407e116ee93f110fbdd216a877e45.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'Spring', 'Construção totalmente metálica. Barril totalmente em metal, receptor e tudo mais que deveria ser de metal. Protetor de bochecha de atirador ajustável. Visão traseira ajustável. Seleção de fogo totalmente automática e semiautomática. Hop-Up Ajustável. Compartimento de bateria realista e discreto, pode precisar de assistência de ferramenta para abrir o compartimento da bateria. Cobertura contra poeira tratada com fosfato. Polímero com acabamento de imitação de madeira.

Especificações: Comprimento: 1219mm; Peso: 3500g; Capacidade do Magazine: 180 rodadas - Mid-Cap; Motor: Short Type; Hop-Up: Sim, Ajustável.', 'https://www.arsenalsports.com/produto/ak-spring-svd-dragunov-with-metal-gearbox-and-wood-sniper-airsoft-rifle-27550.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('ACEBEAM FLASHLIGHT LED 2200L / 1083M', 'ACEBEAM', 136, 'https://www.arsenalsports.com/img/31479/produtos/600/70701f31b8977b3a7f67c2ff217a72be.png', (SELECT id FROM public.categories WHERE slug = 'acessorios'), 'AEG', 'A lanterna ACEBEAM L19 2.0 é o equipamento definitivo para sua próxima viagem de caça ou aventura ao ar livre. Esta lanterna atualizada fornece até 2200 lúmens com uma distância de feixe impressionante de 3.553 pés (1.083 metros) — mais de meia milha! Ela se destaca como a lanterna de caça de maior alcance em sua classe com um diâmetro de cabeça de 55 mm. Os caçadores apreciarão a opção de LED verde, que preserva a visão noturna e minimiza o risco de assustar a presa. Apresentando uma classificação à prova d''água IP68 e alimentada por uma bateria de íons de lítio recarregável 21700, a L19 2.0 foi construída para aqueles que exigem distância de feixe extrema e durabilidade robusta. Luminus SFT40 HI 6500K Max Output: 2200lumens/1083Meters/293222cd. Bateira: 1 x IMR21700NP-510A USB-C Charging.', 'https://www.arsenalsports.com/produto/acebeam-flashlight-led-2200l--1083m-31479.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('ACTION ARMY GBB AAP01 ASSASSIN BLOWBACK PISTOL FLAT DARK EARTH', 'ACTION ARMY', 120, 'https://www.arsenalsports.com/img/17704/produtos/600/f62f04c9989c59a52d454457bf5d2acb.jpg', (SELECT id FROM public.categories WHERE slug = 'pistolas'), 'GBB', 'O primeiro design exclusivo de pistola do Action Army vem com estilo agressivo e desempenho para combinar. Design exclusivo de pistola de alvo, ótimo para plinking de alvo e uso em escaramuças de Airsoft. Modos de disparo semi-automático e totalmente automático selecionáveis! O cano com rosca de 14 mm permite o uso de supressores de Airsoft. Miras de ferro dianteiras e traseiras estilo fibra óptica. Recursos ambidestros e de troca lateral, como o lançamento magnético e a alça de carregamento, otimizam a ergonomia para atiradores destros e canhotos. Usa Magazine GBB compatível com TM g-spec. Trilho acessório de 20 mm montado em cano removível.', 'https://www.arsenalsports.com/produto/action-army-gbb-aap01-assassin-blowback-pistol-flat-dark-earth-17704.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('ACTION ARMY GBB AAP01C ASSASSIN COMPACT BLOWBACK AIRSOFT PISTOL BLACK', 'ACTION ARMY', 120, 'https://www.arsenalsports.com/img/24655/produtos/600/a40ae4880175c539fe0ed3dd34eff8ff.jpg', (SELECT id FROM public.categories WHERE slug = 'pistolas'), 'GBB', 'Bolts ergonomic design and high performance. Blowback gas system allows for semi-automatic and full-auto firing modes.', 'https://www.arsenalsports.com/produto/action-army-gbb-aap01c-assassin-compact-blowback-airsoft-pistol-black-24655.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('ACTION ARMY SPRING SNIPER BOLT ACTION ACC-T10 AIRSOFT RIFLE FLAT DARK EARTH COMBO', 'ACTION ARMY', 299, 'https://www.arsenalsports.com/img/14690/produtos/600/39d85317c63f2c2a58673fe60bf2a92c.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'Spring', 'A Action Army Company (AAC) foi fundada no ano de 2010 e atualmente está localizada em Taiwan. Originalmente, a Action Army Company focou na criação de peças de alto desempenho para a GearBox, mas expandiu a criação de peças externas CNC, como o chassi AAC-21. Action Army tem a capacidade de máquina CNC, die cast, forjar, carimbo, revestimento em pó, etc. suas partes para a maior durabilidade e excelente aparência consistente. Seu objetivo é construir novos produtos com um material muito mais forte, porém mais leve, para obter o máximo de eficiência de sua pistola de airsoft interna e externamente.', 'https://www.arsenalsports.com/produto/action-army-spring-sniper-bolt-action-acct10-airsoft-rifle-flat-dark-earth-combo-14690.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('ACTION ARMY SPRING SNIPER BOLT ACTION ACC-T10 AIRSOFT RIFLE BLACK', 'ACTION ARMY', 299, 'https://www.arsenalsports.com/img/15231/produtos/600/668f44f8649485a582c33adfe909d0d2.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'Spring', 'A Action Army Company (AAC) foi fundada no ano de 2010 e atualmente está localizada em Taiwan. Originalmente, a Action Army Company focou na criação de peças de alto desempenho para a GearBox, mas expandiu a criação de peças externas CNC, como o chassi AAC-21. Action Army tem a capacidade de máquina CNC, die cast, forjar, carimbo, revestimento em pó, etc. suas partes para a maior durabilidade e excelente aparência consistente. Seu objetivo é construir novos produtos com um material muito mais forte, porém mais leve, para obter o máximo de eficiência de sua pistola de airsoft interna e externamente.', 'https://www.arsenalsports.com/produto/action-army-spring-sniper-bolt-action-acct10-airsoft-rifle-black-15231.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('AGM AEG MP44 REAL WOOD WWII AIRSOFT RIFLE BLACK', 'AGM', 320, 'https://www.arsenalsports.com/img/34836/produtos/600/b4c14e16e947ecc87cfaef233e8889aa.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'AEG', 'A AGM MP056B é uma réplica autêntica do fuzil automático alemão StG 44 (MP 44), primorosamente fabricada em metal, que certamente encantará jogadores de airsoft e entusiastas de reconstituições históricas. Feita principalmente de alumínio e aço, oferece qualidade de construção incomparável. O tubo de gás em metal, a cobertura do cano e o espaçoso carregador de alta capacidade para 400 BBs garantem uma experiência de jogo autêntica.

A coronha de madeira, com espaço dedicado para a bateria, contribui para o visual realista e o conforto do usuário. O seletor de modo de disparo horizontal e a possibilidade de ajustar o sistema hop-up abrindo a tampa de ejeção de projéteis são características que tornam esta réplica não apenas visualmente atraente, mas também excepcionalmente funcional e interessante para o entusiasta mais exigente.

- No coração desta réplica da MP 44 está uma robusta gearbox v2, repleta de componentes reforçados que garantem desempenho e durabilidade excepcionais.
- Engrenagens de aço montadas em rolamentos de 8 mm
- Cilindro cromado
- Cabeça do pistão direcional com rolamentos
- Guia de mola de metal
- Magazine de Hi-Cap e até 400 Rounds
- **ACOMPANHA 02 MAGAZINES EXTRAS. TOTALIZANDO 03 MAGAZINES**

**\*As descrições e especificações dos produtos são de responsabilidade do fabricante. Não nos responsabilizamos por imprecisões ou inconsistências nas informações ou imagens exibidas**', 'https://www.arsenalsports.com/produto/agm-aeg-mp44-real-wood-wwii-airsoft-rifle-black-34836.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('AGM SPRING SNIPER L96 AIRSOFT RIFLE BLACK', 'AGM', 120, 'https://www.arsenalsports.com/img/26630/produtos/600/ad7994d04b2c297dd9ffd06e0be45f7e.png', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'Spring', 'Corpo de polímero moldado por injeção leve e durável, Barril externo de metal de uma peça, Receptor e parafuso de metal, Trilho acessório superior de metal de 20 mm para montagem de óptica, Design de disparo único e ação de ferrolho, Pontos de amarração dianteiros e traseiros, Compatível com sistema APS2, Chassi de atirador ergonômico. ACOMPANHA 01 MAGAZINE EXTRA. TOTALIZANDO 02 MAGAZINES.', 'https://www.arsenalsports.com/produto/agm-spring-sniper-l96-airsoft-rifle-black-26630.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('AGM SPRING SNIPER L96 AIRSOFT RIFLE OD GREEN', 'AGM', 120, 'https://www.arsenalsports.com/img/26631/produtos/600/7cae957b8dd62fc1b4d62bd06554fe4f.png', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'Spring', 'Corpo de polímero moldado por injeção leve e durável; Barril externo de metal de uma peça; Receptor e parafuso de metal; Trilho acessório superior de metal de 20 mm para montagem de óptica; Design de disparo único e ação de ferrolho; Pontos de amarração dianteiros e traseiros; Compatível com sistema APS2; Chassi de atirador ergonômico; ACOMPANHA 01 MAGAZINE EXTRA. TOTALIZANDO 02 MAGAZINES.', 'https://www.arsenalsports.com/produto/agm-spring-sniper-l96-airsoft-rifle-od-green-26631.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('AGM SPRING SNIPER SVD DRAGUNOV AIRSOFT RIFLE BLACK', 'AGM', 185, 'https://www.arsenalsports.com/img/26632/produtos/600/3d8e08cc7c8285af44ce376eeba21eb0.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'Spring', 'A ação do ferrolho fácil de usar não requer gás ou baterias. O estoque dobrável facilita o transporte e o armazenamento. Construção durável em liga metálica. O trilho lateral permite a montagem de escopos ou suportes de trilho. ACOMPANHA 01 MAGAZINE EXTRA. TOTALIZANDO 02 MAGAZINES.', 'https://www.arsenalsports.com/produto/agm-spring-sniper-svd-dragunov-airsoft-rifle-black-26632.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('AGM SPRING SNIPER SVD DRAGUNOV AIRSOFT RIFLE BLACK & WOOD', 'AGM', 185, 'https://www.arsenalsports.com/img/26633/produtos/600/e88d3b5e75065f96a4b729fdd1d5f9b0.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'Spring', 'A ação do ferrolho fácil de usar não requer gás ou baterias. O estoque dobrável facilita o transporte e o armazenamento. Construção durável em liga metálica. Utiliza polímero com aparência de madeira. O trilho lateral permite a montagem de escopos ou suportes de trilho. ACOMPANHA 01 MAGAZINE EXTRA. TOTALIZANDO 02 MAGAZINES. Potência de até 420 FPS. Comprimento: 920 mm-1180 mm (dobrado/desdobrado). Modo de disparo: Bolt Spring Action. Capacidade do Magazine: 30 Rounds.', 'https://www.arsenalsports.com/produto/agm-spring-sniper-svd-dragunov-airsoft-rifle-black--wood-26633.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('AGM SPRING SNIPER VSR-10 AIRSOFT RIFLE BLACK & WOOD', 'AGM', 110, 'https://www.arsenalsports.com/img/26636/produtos/600/da7d9ddf738d861e78850cecc87d2af1.png', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'Spring', 'O AGM MP001 é o rifle perfeito para quem deseja entrar no mundo do atirador de Airsoft. Baseado no infame design Tokyo Marui VSR 10, o AGM MP001 está disponível por uma fração do preço, usando peças comparáveis ??no interior. Uma coronha lisa e sólida construída em plástico ABS é resistente, mas leve, e mantém o ferrolho de aço no lugar, tornando todo o rifle muito sólido. O trilho de acessórios integrado de 20 mm é perfeito para montar escopos ou outras ópticas, e o terminal de fixação do bipé instalado está pronto para ser usado assim que sai da caixa. Também estão incluídos dois pontos de montagem da tipoia - um na frente da coronha e outro na parte traseira - o que significa que você está pronto para prender sua tipoia de dois pontos favorita assim que sai da caixa. ACOMPANHA 01 MAGAZINE EXTRA. TOTALIZANDO 02 MAGAZINES.', 'https://www.arsenalsports.com/produto/agm-spring-sniper-vsr10-airsoft-rifle-black--wood-26636.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('AGM SPRING SNIPER VSR-10 AIRSOFT RIFLE BLACK', 'AGM', 110, 'https://www.arsenalsports.com/img/26635/produtos/600/fb8578562fd9bdcf23cf753fe3c468fe.png', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'Spring', 'O AGM MP001 é o rifle perfeito para quem deseja entrar no mundo do atirador de Airsoft. Baseado no infame design Tokyo Marui VSR 10, o AGM MP001 está disponível por uma fração do preço, usando peças comparáveis ??no interior. Uma coronha lisa e sólida construída em plástico ABS é resistente, mas leve, e mantém o ferrolho de aço no lugar, tornando todo o rifle muito sólido. O trilho de acessórios integrado de 20 mm é perfeito para montar escopos ou outras ópticas, e o terminal de fixação do bipé instalado está pronto para ser usado assim que sai da caixa. Também estão incluídos dois pontos de montagem da tipoia - um na frente da coronha e outro na parte traseira - o que significa que você está pronto para prender sua tipoia de dois pontos favorita assim que sai da caixa. ACOMPANHA 01 MAGAZINE EXTRA. TOTALIZANDO 02 MAGAZINES.', 'https://www.arsenalsports.com/produto/agm-spring-sniper-vsr10-airsoft-rifle-black-26635.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('AMOEBA AEG M4 AM-003 CARBINE AIRSOFT RIFLE BLACK', 'AMOEBA', 99, 'https://www.arsenalsports.com/img/13306/produtos/600/6d6e26874d226f4d20b29effa3721a9e.png', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'AEG', 'Uma série das mais recentes AM-003 de Amoeba Airsoft é baseada em um design bem conhecido de rifles de asHop Up AR, mas essas AM-003s foram consideravelmente modificadas e enriquecidas com muitos detalhes de construção e soluções técnicas interessantes, que melhoram não apenas sua funcionalidade, mas também sua aparência. Graças às suas dimensões compactas, o AM-001 é muito útil e constitui uma ferramenta perfeita durante as ações do airsoft CQB.', 'https://www.arsenalsports.com/produto/amoeba-aeg-m4-am003-carbine-airsoft-rifle-black-13306.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('AMOEBA AEG M4 AM-003 CARBINE AIRSOFT RIFLE DESERT', 'AMOEBA', 99, 'https://www.arsenalsports.com/img/13307/produtos/600/bb61445bd49ab79b4a1506aa4e58448e.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'AEG', 'Uma série das mais recentes AM-003 de Amoeba Airsoft é baseada em um design bem conhecido de rifles de asHop Up AR, mas essas AM-003s foram consideravelmente modificadas e enriquecidas com muitos detalhes de construção e soluções técnicas interessantes, que melhoram não apenas sua funcionalidade, mas também sua aparência. Graças às suas dimensões compactas, o AM-001 é muito útil e constitui uma ferramenta perfeita durante as ações do airsoft CQB.', 'https://www.arsenalsports.com/produto/amoeba-aeg-m4-am003-carbine-airsoft-rifle-desert-13307.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('AMOEBA AEG AM-007 M4 CCR AIRSOFT RIFLE DESERT', 'AMOEBA', 0, 'https://www.arsenalsports.com/img/18823/produtos/600/5fe1d6e3c1cabbf99bf81a2224436697.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'AEG', 'Construído a partir de material de polímero reforçado extremamente resistente. O design compacto é perfeito para CQB. Punho de pistola texturizado, estoque ajustável, fácil acesso ao compartimento da bateria, visão frontal e traseira removível, botão de liberação de magazine ampliado para fácil uso. GearBox totalmente metálica com partes internas reforçadas. Sistema de controle eletrônico de disparo exclusivo do ARES (EFCS - Safe / Semi / 3rd Burst / Full Auto). Caixa de velocidades programável através da unidade de programação EFCS (vendida separadamente). Receptor de topo plano para óptica e acessórios montados em Picatinny / Weaver de 20 mm. HandGuard RIS de polímero de alto impacto. Alça vertical incluída.', 'https://www.arsenalsports.com/produto/amoeba-aeg-am007-m4-ccr-airsoft-rifle-desert-18823.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('AMOEBA AEG M4 AM-007 CCR AIRSOFT RIFLE BLACK', 'AMOEBA', 159, 'https://www.arsenalsports.com/img/28641/produtos/600/6ae0e8e1252dfa534b983def46f52cf8.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'AEG', 'Construído a partir de material de polímero reforçado extremamente resistente. O design compacto é perfeito para CQB. Punho de pistola texturizado. Estoque ajustável. Fácil acesso ao compartimento da bateria. Visão frontal e traseira removível. Botão de liberação de Magazine ampliado para fácil uso. GearBox totalmente metálica com partes internas reforçadas. Sistema de controle eletrônico de disparo exclusivo do ARES (EFCS - Safe / Semi / 3rd Burst / Full Auto). Caixa de velocidades programável através da unidade de programação EFCS (vendida separadamente). Receptor de topo plano para óptica e acessórios montados em Picatinny / Weaver de 20 mm. HandGuard RIS de polímero de alto impacto. Alça vertical incluída.', 'https://www.arsenalsports.com/produto/amoeba-aeg-m4-am007-ccr-airsoft-rifle-black-28641.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('AMOEBA AEG M4 AM-009 13" CARBINE AIRSOFT RIFLE DESERT', 'AMOEBA', 0, 'https://www.arsenalsports.com/img/10036/produtos/600/9cc33aeebd03a4e26bd223ee0a276aaf.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'AEG', 'Esse Rifle de Airsoft vem com um sistema de mola de troca rápida, permitindo assim que você atualize ou reduza rapidamente o FPS (Pés por segundo) da sua arma com facilidade.

Este rifle estilo AMOEBA faz parte do novo sistema de GearBox EFCS da ARES (Electronic Firing Control System), pois permite que a GearBox seja programada para ser Semi, 3 round burst ou full auto usando o Programador Ares Amoeba Electronic Gearbox Programmer EFCS.', 'https://www.arsenalsports.com/produto/amoeba-aeg-m4-am009-13-carbine-airsoft-rifle-desert-10036.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('AMOEBA AEG M4 AM-008 CARBINE AIRSOFT RIFLE DESERT', 'AMOEBA', 200, 'https://www.arsenalsports.com/img/33274/produtos/600/72c2eb23b5d41cf356d73d43ad5026cb.png', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'AEG', 'Construído com material de polímero reforçado extremamente resistente. O design compacto é perfeito para CQB. Punho de pistola texturizado. Estoque de crane ajustável. Vista frontal virada para cima, visão traseira removível. Botão de liberação de Magazine ampliado para facilitar o uso. Sistema eletrônico de controle de queima eletrônico exclusivo da ARES (EFCS - Safe / Semi / 3rd Burst / Full Auto). GearBox programável via unidade de programação EFCS (vendida separadamente). 

Especificações:
- BlowBack: Não
- Comprimento: 670mm - 750mm
- Peso: 2080 Gramas
- Material: Metal e Polímero
- Potência de até 380 FPS
- Modo de Disparo: Safe, Semi-Auto, Full-Auto
- GearBox: Ver. 2 Modificada
- Hop-Up: Ajustável
- Capacidade do Magazine: 300 Rounds
- MOSFET/ETU: Sim
- Quick Spring Change System: Sim', 'https://www.arsenalsports.com/produto/amoeba-aeg-m4-am008-carbine-airsoft-rifle-desert-33274.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('AMOEBA AEG M4 AM-013 12" CARBINE AIRSOFT RIFLE DESERT', 'AMOEBA', 249, 'https://www.arsenalsports.com/img/7703/produtos/600/f662f5c9993c66d531b056e793bdb6a5.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'AEG', 'Construído a partir de polímero reforçado com fibra de nylon incrivelmente resistente. Handguard de alumínio CNC 6063 com duas seções de trilho Picatinny e duas paradas de mão. Supressor simulado de alumínio montado no handguard. Design compacto é perfeito para CQB.', 'https://www.arsenalsports.com/produto/amoeba-aeg-m4-am013-12-carbine-airsoft-rifle-desert-7703.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('AMOEBA AEG M4 MUTANT AMM5 AIRSOFT RIFLE BLACK', 'AMOEBA', 219, 'https://www.arsenalsports.com/img/17952/produtos/600/6420324d0c6ba8026907072c17e87f77.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'AEG', 'Tipo AEG, GearBox EFCS, Material de fibra de nylon, alumínio, metal, Tipo de Disparo: Fire Mode Totalmente Automático / Semi Auto / Seguro (O Fire Mode pode ser personalizado pelo Programador de GearBox Eletrônica), Material da GearBox liga de zine fundido, Hop-Up ajustável, Magazine: 140 Rounds, Liberação Rápida de Mola, Tipos de bateria: 7,4v - 11,1v, Peso 2120g, Comprimento 520-615 mm. VEM COM 01 MAGAZINE 140 ROUNDS MID-CAP.', 'https://www.arsenalsports.com/produto/amoeba-aeg-m4-mutant-amm5-airsoft-rifle-black-17952.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('AMOEBA AEG M4 AM-015 CARBINE AIRSOFT RIFLE BLACK', 'AMOEBA', 249, 'https://www.arsenalsports.com/img/10037/produtos/600/e1a251855f860fc69e81286bda826a87.png', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'AEG', 'Tanto o rifle quanto o calibre utilizados foram desenvolvidos em estreita cooperação com unidades de operações especiais americanas para criar um substituto adequado e eficaz para o HK MP5 e sistemas de armas CQB similares. O rifle é projetado para ser muito conveniente para uso militar, onde a plataforma CAR-15 é emitida e de uso comum, já que muitas similaridades existiriam nos controles de fogo, manipulação de armas e magazines. Finalmente, a versão de airsoft chegou. Muitas pessoas foram e personalizaram sua própria versão, mas a ARES é a única empresa que ouviu e partiu para projetar o AM-015, que se assemelhava muito ao AAC Badger PDW da AAC. Ele se encaixa com a linha Amoeba, já que o receptor não mudou, mas eles conseguiram adicionar o elegante estoque extensível HB, um HandGuard de flutuação livre e um amplificador saindo da frente. O HandGuard é um pouco mais curto, adequado para quem prefere o comprimento da arma menor. Funciona com o Programador de Caixa de Velocidades Eletrônico (EFCS) ARES / Amoeba para a GearBox do Sistema de Controle de Acionamento Eletrônico ARES, para que você possa configurar o seu AEG para explodir fogo, se preferir. A resposta do acionador é excelente e funciona melhor com uma bateria de 7,4V PEQ que é armazenada em um pequeno compartimento do material. É um pouco inquieto, mas se encaixa perfeitamente para que você não fique chocado.', 'https://www.arsenalsports.com/produto/amoeba-aeg-m4-am015-carbine-airsoft-rifle-black-10037.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('AMOEBA AEG M4 MUTANT AMM7 AIRSOFT RIFLE DESERT', 'AMOEBA', 219, 'https://www.arsenalsports.com/img/17955/produtos/600/cc3f363e1c84adcf8c1e30ea308e7ee1.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'AEG', 'Série AMOEBA M4 redesenhada, receptor superior e inferior robusto e leve em polímero, guarda-mão M-LOK de liberação rápida em alumínio CNC, comprimentos de cano e guarda-mão altamente configuráveis.', 'https://www.arsenalsports.com/produto/amoeba-aeg-m4-mutant-amm7-airsoft-rifle-desert-17955.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('AMOEBA AEG M4 MUTANT AMM9 AIRSOFT RIFLE BLACK', 'AMOEBA', 219, 'https://www.arsenalsports.com/img/17956/produtos/600/3c4ac25dbcf1f86c13dfdbaebd562692.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'AEG', 'Tipo AEG, GearBox EFCS, Material de fibra de nylon, alumínio, metal, Tipo de Disparo: Fire Mode Totalmente Automático / Semi Auto / Seguro, Material da GearBox liga de zine fundido, Hop-Up ajustável, Magazine: 140 Rounds, Liberação Rápida de Mola, Tipos de bateria: 7,4v - 11,1v, Peso 2440g, Comprimento 680-750mm. VEM COM 01 MAGAZINE 140 ROUNDS MID-CAP.', 'https://www.arsenalsports.com/produto/amoeba-aeg-m4-mutant-amm9-airsoft-rifle-black-17956.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('AMOEBA SPRING SNIPER STRIKER AS01 AIRSOFT RIFLE BLACK', 'AMOEBA', 148, 'https://www.arsenalsports.com/img/11364/produtos/600/535451a4452e25d1a2baa5695a20026e.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'Spring', 'O rifle sniper AMOEBA Striker S1 é um rifle Airsoft avançado, compacto e de precisão projetado em torno dos conceitos de modularidade, funcionalidade e minimalismo. Com todos os recursos úteis que você precisa e quer, e nenhum dos sinos e assobios que um Sniper Airsoft não quer, o AMOEBA S1 sai da caixa pronto para lutar. Construído sobre a base de um chassi de polímero modular que apresenta um estoque ajustável, riser e grip, o atacante S1 pode ser personalizado para se adequar ao atirador individual.', 'https://www.arsenalsports.com/produto/amoeba-spring-sniper-striker-as01-airsoft-rifle-black-11364.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('AMOEBA SPRING SNIPER STRIKER AS01 AIRSOFT RIFLE DESERT', 'AMOEBA', 148, 'https://www.arsenalsports.com/img/11365/produtos/600/5fb4ac4f8ec7e2954eb40f5527d1c780.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'Spring', 'O rifle sniper AMOEBA Striker S1 é um rifle Airsoft avançado, compacto e de precisão projetado em torno dos conceitos de modularidade, funcionalidade e minimalismo. Com todos os recursos úteis que você precisa e quer, e nenhum dos sinos e assobios que um Sniper Airsoft não quer, o AMOEBA S1 sai da caixa pronto para lutar. Construído sobre a base de um chassi de polímero modular que apresenta um estoque ajustável, riser e grip, o atacante S1 pode ser personalizado para se adequar ao atirador individual.', 'https://www.arsenalsports.com/produto/amoeba-spring-sniper-striker-as01-airsoft-rifle-desert-11365.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('AMOEBA SPRING SNIPER STRIKER AS01 AIRSOFT RIFLE URBAN GREY', 'AMOEBA', 148, 'https://www.arsenalsports.com/img/11700/produtos/600/531e6f8d9dc5b81c36471c5e28f623c4.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'Spring', 'O rifle sniper AMOEBA Striker S1 é um rifle Airsoft avançado, compacto e de precisão projetado em torno dos conceitos de modularidade, funcionalidade e minimalismo. Com todos os recursos úteis que você precisa e quer, e nenhum dos sinos e assobios que um Sniper Airsoft não quer, o AMOEBA S1 sai da caixa pronto para lutar. Construído sobre a base de um chassi de polímero modular que apresenta um estoque ajustável, riser e grip, o atacante S1 pode ser personalizado para se adequar ao atirador individual. O receptor de metal abriga o Compact Power Bolt da AMOEBA, que fornece ao atirador a mesma potência com a qual ele está acostumado, com um comprimento de tração muito mais curto.', 'https://www.arsenalsports.com/produto/amoeba-spring-sniper-striker-as01-airsoft-rifle-urban-grey-11700.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('AMOEBA SPRING SNIPER STRIKER AS01 AIRSOFT RIFLE OD GREEN', 'AMOEBA', 148, 'https://www.arsenalsports.com/img/11531/produtos/600/c794b017bb6362642eabb518b03c0e03.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'Spring', 'O rifle sniper AMOEBA Striker S1 é um rifle Airsoft avançado, compacto e de precisão projetado em torno dos conceitos de modularidade, funcionalidade e minimalismo. Com todos os recursos úteis que você precisa e quer, e nenhum dos sinos e assobios que um Sniper Airsoft não quer, o AMOEBA S1 sai da caixa pronto para lutar.', 'https://www.arsenalsports.com/produto/amoeba-spring-sniper-striker-as01-airsoft-rifle-od-green-11531.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('AMOEBA SPRING SNIPER STRIKER AS03 AIRSOFT RIFLE BLACK', 'AMOEBA', 109, 'https://www.arsenalsports.com/img/16148/produtos/600/aefd419411cf75bd477a2a6a7909e424.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'Spring', 'A terceira iteração do famoso rifle sniper STRIKER chega até nós em uma configuração de "pistola" ultra compacta. Esta pistola apresenta a mesma ação de golpe curto encontrada nas gerações anteriores e se baseia na ação aprimorada encontrada no STRIKER 02. Embora seu formato ultra compacto possa ser incomum, ele ainda possui precisão excepcional e toda a modularidade encontrada nas armas anteriores. Seu corpo de polímero leve torna muito leve; de fato, esta pistola pode ser disparada com as mãos, excelente para uma segunda ou terceira opção quando é necessário um único tiro de precisão.', 'https://www.arsenalsports.com/produto/amoeba-spring-sniper-striker-as03-airsoft-rifle-black-16148.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('AMOEBA SPRING SNIPER STRIKER AS03 AIRSOFT RIFLE OD GREEN', 'AMOEBA', 109, 'https://www.arsenalsports.com/img/16151/produtos/600/c0ec2c39a189ece181670297d1ef24d3.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'Spring', 'A terceira iteração do famoso rifle sniper STRIKER chega até nós em uma configuração de "pistola" ultra compacta. Esta pistola apresenta a mesma ação de golpe curto encontrada nas gerações anteriores e se baseia na ação aprimorada encontrada no STRIKER 02. Embora seu formato ultra compacto possa ser incomum, ele ainda possui precisão excepcional e toda a modularidade encontrada nas armas anteriores. Seu corpo de polímero leve torna muito leve; de fato, esta pistola pode ser disparada com as mãos, excelente para uma segunda ou terceira opção quando é necessário um único tiro de precisão.', 'https://www.arsenalsports.com/produto/amoeba-spring-sniper-striker-as03-airsoft-rifle-od-green-16151.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('AMOEBA SPRING SNIPER STRIKER AS03 AIRSOFT RIFLE TAN', 'AMOEBA', 109, 'https://www.arsenalsports.com/img/16150/produtos/600/aa57779ecdba68324ab08034a9bd3362.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'Spring', 'A terceira iteração do famoso rifle sniper STRIKER chega até nós em uma configuração de ''pistola'' ultra compacta. Esta pistola apresenta a mesma ação de golpe curto encontrada nas gerações anteriores e se baseia na ação aprimorada encontrada no STRIKER 02. Embora seu formato ultra compacto possa ser incomum, ele ainda possui precisão excepcional e toda a modularidade encontrada nas armas anteriores. Seu corpo de polímero leve torna muito leve; de fato, esta pistola pode ser disparada com as mãos, excelente para uma segunda ou terceira opção quando é necessário um único tiro de precisão.', 'https://www.arsenalsports.com/produto/amoeba-spring-sniper-striker-as03-airsoft-rifle-tan-16150.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('AMOEBA SPRING SNIPER STRIKER AS03 AIRSOFT RIFLE URBAN GREY', 'AMOEBA', 109, 'https://www.arsenalsports.com/img/15798/produtos/600/d6357091d12786bb1ea2c5b34394b2d6.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'Spring', 'A terceira iteração do famoso rifle sniper STRIKER chega até nós em uma configuração ''pistola'' ultracompacta. Esta arma possui a mesma ação de curto curso encontrada nas gerações anteriores e se baseia na ação aprimorada encontrada no STRIKER 02. Embora seu formato ultracompacto possa ser incomum, ele ainda possui precisão excepcional e toda a modularidade encontrada nas armas anteriores. Seu corpo de polímero leve torna muito leve, na verdade, esta arma pode ser atirada de mãos dadas, excelente para uma segunda ou terceira opção quando é necessário um único tiro de precisão para ser levado.', 'https://www.arsenalsports.com/produto/amoeba-spring-sniper-striker-as03-airsoft-rifle-urban-grey-15798.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('AMOEBA SPRING SNIPER STRIKER T01 AIRSOFT RIFLE BLACK', 'AMOEBA', 155, 'https://www.arsenalsports.com/img/18824/produtos/600/eaea01c0467c7955decd3c48a80634be.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'Spring', 'Alça de carregamento de baixo perfil, Botão de lançamento de nova Magazine, G2 (Geração 2) Receptor superior: 90 graus Sear, Trilho superior de comprimento total, Pino de bolt fixo, Segurança Avançada, Gatilho Totalmente Ajustável, O carregamento é bloqueado quando a segurança está ativada, Estoque de fundo tático totalmente ajustável com Magwell sobressalente, Peça de bochecha ajustável e almofada de bochecha, Novo Indicador de Carga, Compatível com peças AS Series.', 'https://www.arsenalsports.com/produto/amoeba-spring-sniper-striker-t01-airsoft-rifle-black-18824.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('AMOEBA SPRING SNIPER STRIKER T01 AIRSOFT RIFLE TAN', 'AMOEBA', 155, 'https://www.arsenalsports.com/img/18825/produtos/600/77ec3617cbe4aaeaae60dc5318936b0d.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'Spring', 'Alça de carregamento de baixo perfil
Botão de lançamento de nova Magazine
G2 (Geração 2) Receptor superior:
- 90 graus Sear
- Trilho superior de comprimento total
- Pino de bolt fixo
- Segurança Avançada
- Gatilho Totalmente Ajustável
- O carregamento é bloqueado quando a segurança está ativada
- Estoque de fundo tático totalmente ajustável com Magwell sobressalente
- Peça de bochecha ajustável e almofada de bochecha
- Novo Indicador de Carga
- Compatível com peças AS Series

**Especificações:**
- Material de construção: Fibra de nylon / CNC 6063 /
- Compartimento de metal Capacidade: 45 rounds (6mm BBs)
- Comprimento: 1070mm
- Peso: 3000g
- Sistema: Bolt Action', 'https://www.arsenalsports.com/produto/amoeba-spring-sniper-striker-t01-airsoft-rifle-tan-18825.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('AMOEBA SPRING SNIPER STRIKER T01 AIRSOFT RIFLE URBAN GREY', 'AMOEBA', 155, 'https://www.arsenalsports.com/img/18048/produtos/600/b30b630d46171a8857219f712380645f.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'Spring', 'Alça de carregamento de baixo perfil, Botão de lançamento de nova Magazine, G2 (Geração 2) Receptor superior, Segurança Avançada, Gatilho Totalmente Ajustável, Isso é bloqueado quando a segurança está ativada, Estoque de fundo tático totalmente ajustável com Magwell sobressalente, Peça de bochecha ajustável e almofada de bochecha. Novo Indicador de Carga. Compatível com peças AS Series.', 'https://www.arsenalsports.com/produto/-amoeba-spring-sniper-striker-t01-airsoft-rifle-urban-grey-18048.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('APS AEG ASK201 AK47 BATTLE WORN VERSION FULL METAL BLOWBACK AIRSOFT RIFLE WOOD', 'APS', 280, 'https://www.arsenalsports.com/img/22250/produtos/600/2af8bd96716d0d4373f5ea7eba449f4a.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'GBB', 'Esta é uma arma típica dos ''bandidos'' nos jogos da Airsoft. Esta arma de metal real com acabamento em madeira fará você se sentir muito Eastern Bloc. O guarda de mão e estoque de bochecha são feitos com madeira real. O tamanho e o peso da arma são muito próximos de um AK real. Isso proporciona extremo realismo e é muito divertido de usar para todos os jogadores da Airsoft. O grão da madeira é único e depende totalmente da estrutura original da fonte de madeira. Portanto, cada produção de ASK201 é única, preciosa e distinta.', 'https://www.arsenalsports.com/produto/aps-aeg-ask201-ak47-battle-worn-version-full-metal-blowback-airsoft-rifle-wood-22250.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('APS AEG ASK205 AK74U AGING VERSION FULL METAL BLOWBACK AIRSOFT RIFLE WOOD', 'APS', 28, 'https://www.arsenalsports.com/img/16870/produtos/600/cc93024d17ecb77d2a0f8c0ae6c5e5b1.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'GBB', 'GearBox v.3 HYBRiD com sistema de troca rápida de molas (100% compatível com peças padrão da TM)
Mola 110 m / com potência de até 370 FPS
Superfície lisa e polida da GearBox com proteção contra corrosão
Engrenagens de aço
Rolamentos lisos de aço de 8mm
Cabeça de pistão direcional do rolamento
Cilindro tipo 1 com furo
Bico de alumínio selado
A guia da mola do rolamento possui 4 pernas de travamento em vez de 2 (o que difere das guias de mola existentes no mercado) para proteger adicionalmente a mola durante o disparo.
Sistema EEB
O tambor interno é feito de aço inoxidável com um diâmetro de 6,03 mm', 'https://www.arsenalsports.com/produto/aps-aeg-ask205-ak74u-aging-version-full-metal-blowback-airsoft-rifle-wood-16870.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('APS AEG ASK205 AK74U BATTLE WORN VERSION FULL METAL BLOWBACK AIRSOFT RIFLE WOOD', 'APS', 256, 'https://www.arsenalsports.com/img/22251/produtos/600/48c8fd7940c54a45e145c3265c16211a.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'GBB', 'A verdadeira versão CQB da nossa série ASK. Seu cano curto e coronha dobrável fazem deste AKSU a arma perfeita para o combate CQB. Se você é um amante do CQB, precisa dar uma boa olhada nessa arma. Esta arma icônica ocupa seu lugar de direito no hall da fama do airsoft. Poderoso, versátil e carrega uma arrogância com seu pedigree impecável. Domine a arena CQB e escolha o APS AK74U. A versão de batalha é feita para colecionador. A pintura de aparência envelhecida oferece um alto grau de realismo de um rifle sendo usado em batalhas. Há muitos processamentos especiais feitos à mão adicionais, como rosca enferrujada, cicatrizes, arranhões. É muito demorado para garantir perspectivas de alta qualidade. Temos certeza que o colecionador vai ficar louco por isso.', 'https://www.arsenalsports.com/produto/aps-aeg-ask205-ak74u-battle-worn-version-full-metal-blowback-airsoft-rifle-wood-22251.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('APS AEG ASK209 AK74 Tactical Advanced Blowback Airsoft Rifle Black', 'APS', 209, 'https://www.arsenalsports.com/img/12809/produtos/600/dd04e27c4689026eae798eba93b695fc.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'GBB', 'Você não experimentou inovação até chegar as mãos no ASK209 PMC AEG pela APS. Ao contrário dos AEG convencionais AK-47, este rifle Airsoft AK possui uma GearBox híbrida da Versão 3 que permite usar duas baterias - ao mesmo tempo. Com fio para a frente e para trás, você pode usar as baterias tipo stick (sob o receptor superior), nunchuck (no estoque do crane) ou tampão. Emparelhados com rolamentos de 8mm e equipados com até duas baterias, o seu AEG aumentará a velocidade de disparo e a resposta do gatilho.', 'https://www.arsenalsports.com/produto/aps-aeg-ask209-ak74-tactical-advanced-blowback-airsoft-rifle-black-12809.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('APS AEG ASK211 AK74U GHOST PATROL VERSION COMPACT FULL METAL BLOWBACK AIRSOFT RIFLE BLACK', 'APS', 184, 'https://www.arsenalsports.com/img/16915/produtos/600/13dea990138248773456285214465031.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'GBB', 'A fully metal construction airsoft rifle with ergonomic design and notable features such as adjustable hop-up, and various shooting modes.', 'https://www.arsenalsports.com/produto/aps-aeg-ask211-ak74u-ghost-patrol-version-compact-full-metal-blowback-airsoft-rifle-black-16915.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('APS AEG ASK212 AK74 RUS ASSAULT BLOWBACK AIRSOFT RIFLE', 'APS', 206, 'https://www.arsenalsports.com/img/24845/produtos/600/7e86ad91c79c3106e202af5217cdcf0c.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'GBB', 'Reinstalação do controle de disparo, o tradicional controle de disparo AK foi removido e substituído por um controle de disparo próximo ao modelo M4, tornando a operação mais conveniente e suave!
- Alavanca de armar extragrande, além da função Electric BlowBack exclusiva da APS, que torna a ação de armar melhor e mais realista quando a placa de culatra se move para frente e para trás!
- Trilho M-Lok, fácil de usar com os acessórios populares do mercado!
- A configuração do silenciador não apenas alonga o cano interno, aumentando assim a potência e a precisão, mas também torna a forma geral da arma mais poderosa.
- Magwell para aumentar a velocidade de troca de magazine, toda configuração profissional!
- Especialmente projetada para miras AK, a ponte alta não bloqueia a visão das miras, o que é mais prático do que estético, e também é um princípio russo!', 'https://www.arsenalsports.com/produto/aps-aeg-ask212-ak74-rus-assault-blowback-airsoft-rifle-24845.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('APS AEG ASR 2E110BR1 2.0 SILVER EDGE BLOWBACK AIRSOFT RIFLE BLACK', 'APS', 225, 'https://www.arsenalsports.com/img/18503/produtos/600/53c4b5e6b8b5a085883ca3fd07fedadb.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'GBB', 'O Rifle Airsoft APS ASR 110 não é apenas uma arma secreta reservada para uso exclusivo das forças especiais e da elite. Este é um rifle atraente, formidável que tem todos os recursos avançados e projetos APS construídos, sem dúvida torna a arma excepcional contra qualquer um em competições. Sua aparência é linda e a arma possui nosso exclusivo guarda mão RTS (Rail Transform System), pois um cano externo e um belíssimo flash hider estão incluídos neste rifle. Possui um interior totalmente atualizado com cabeça do pistão do rolamento, guia da mola do rolamento e gearbox “hibrida”, e por fim um cano interno de aço inoxidável 6.04mm de precisão já vem instalado nesta arma.', 'https://www.arsenalsports.com/produto/aps-aeg-asr-2e110br1-20-silver-edge-blowback-airsoft-rifle-black-18503.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('APS AEG ASK74 AK47 REAL WOOD ELECTRIC BLOWBACK AIRSOFT RIFLE BLACK', 'APS', 189, 'https://www.arsenalsports.com/img/32456/produtos/600/64d74f3579e3a5ae3362549fcce13a94.png', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'GBB', 'Conjunto de cano e receptor totalmente em metal, lindos móveis de madeira genuína, ação elétrica de blowback, base de montagem de luneta integrada na lateral do receptor para montagem de luneta estilo AK, miras dianteiras e traseiras ajustáveis. Potência de até 420FPS, comprimento: 940 mm, GearBox: Ver. 3, capacidade do magazine: 500 Rounds Hi-Cap, motor: Short Type, rosca: 14mm CCW, bateria: 9,6 V Tipo / 7,4 V LiPo, modos de disparo: Safe, Semi-Auto, Full-Auto.', 'https://www.arsenalsports.com/produto/aps-aeg-ask74-ak47-real-wood-electric-blowback-airsoft-rifle-black-32456.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('APS AEG ASR 2E110R1D 2.0 Silver Edge Blowback Airsoft Rifle Desert', 'APS', 225, 'https://www.arsenalsports.com/img/18502/produtos/600/da2e6746c5a513f139d67ef0d1c9d633.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'GBB', 'O Rifle Airsoft APS ASR 110 não é apenas uma arma secreta reservada para uso exclusivo das forças especiais e da elite. Este é um rifle atraente, formidável tem todos os recursos avançados e projetos APS construídos, sem dúvida torna a arma excepcional contra qualquer um em competições. Sua aparência é linda e a arma possui nosso exclusivo guarda mão RTS (Rail Transform System)...', 'https://www.arsenalsports.com/produto/aps-aeg-asr-2e110r1d-20-silver-edge-blowback-airsoft-rifle-desert-18502.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('APS AEG ASR 2E110R1 2.0 SILVER EDGE BLOWBACK AIRSOFT RIFLE BLACK', 'APS', 225, 'https://www.arsenalsports.com/img/18501/produtos/600/79ac17ace17a1219d35176a7a0b08e27.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'GBB', 'O Rifle Airsoft APS ASR 110 não é apenas uma arma secreta reservada para uso exclusivo das forças especiais e da elite. Este é um rifle atraente, formidável tem todos os recursos avançados e projetos APS construídos, sem dúvida torna a arma excepcional contra qualquer um em competições. Sua aparência é linda e a arma possui nosso exclusivo guarda mão RTS (Rail Transform System), pois um cano externo e um belíssimo flash hider estão incluídos neste rifle. Possui um interior totalmente atualizado com cabeça do pistão do rolamenta, guia da mola do rolamento e gearbox “hibrida”, e por fim um cano interno de aço inoxidável 6.04mm de precisão já vem instalado nesta arma. Pois o desempenho e a aparência elegante, combinando com nossos acabamentos de alta qualidade, tornam essa arma incomparável com grande parte da concorrência, é um rifle de bom alcance e vai te dar muitos sucessos no campo de batalha. Sem dúvida a série APS ASR 110, permite que o usuário personalize e atualize os elementos externos da arma para se adequar a diferentes cenários de jogos do airsoft facilmente. O APS ASR 110 possui de fábrica blowback, que é um sistema de imitação de ejeção de cápsulas de um rifle real, o que oferece uma operação ainda mais realista. Rifle extremamente robusto e tático, com um desempenho incrível no campo de batalha.', 'https://www.arsenalsports.com/produto/aps-aeg-asr-2e110r1-20-silver-edge-blowback-airsoft-rifle-black-18501.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('APS AEG ASR 2E112R3 2.0 HANDGUARD 10" SILVER EDGE BLOWBACK AIRSOFT RIFLE', 'APS', 225, 'https://www.arsenalsports.com/img/18499/produtos/600/562fcb75a5dbc2b2e3407689d4b4fc85.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'GBB', 'Quando a APS começou a desenvolver a GearBox Silver Edge, eles queriam trazer ao mercado um sistema ultra-suave, com baixo consumo de amperagem e ultra-confiável com grande potencial de atualização. A mais nova iteração da GearBox Silver Edge chamada eSilver Edge pega tudo o que tornou o original excelente e o aprimora. O recém-desenvolvido chipset SDU ™ (Super Dynamic Unit) avançado monitora o consumo de amperagem de tiro a tiro e cortará a energia da GearBox se a corrente aumentar muito antes de causar danos à sua arma. Para melhorar o desempenho do gatilho, a caixa de velocidades eSilver Edge possui um gatilho micro switch que funciona junto com o chipset SDU ™ para uma resposta quase instantânea do gatilho (tão rápido quanto 0,02 segundos). Quando combinado com um gatilho de golpe curto, os usuários podem atingir uma incrível taxa de tiro semi-automática. Além das peças internas reforçadas, o próprio corpo da GearBox foi bastante reforçado para suportar o estresse de até uma mola M190.', 'https://www.arsenalsports.com/produto/aps-aeg-asr-2e112r3-20-handguard-10-silver-edge-blowback-airsoft-rifle-black-18499.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('APS AEG ASR 2E112R2 2.0 HANDGUARD 10" SILVER EDGE BLOWBACK AIRSOFT RIFLE BLACK', 'APS', 225, 'https://www.arsenalsports.com/img/18498/produtos/600/5ab5c9960e32e3f2718aaa8b1b425f50.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'GBB', 'Quando a APS começou a desenvolver a GearBox Silver Edge, eles queriam trazer ao mercado um sistema ultra-suave, com baixo consumo de amperagem e ultra-confiável com grande potencial de atualização. A mais nova iteração da GearBox Silver Edge chamada eSilver Edge pega tudo o que tornou o original excelente e o aprimora. O recém-desenvolvido chipset SDU ™ (Super Dynamic Unit) avançado monitora o consumo de amperagem de tiro a tiro e cortará a energia da GearBox se a corrente aumentar muito antes de causar danos à sua arma. Para melhorar o desempenho do gatilho, a caixa de velocidades eSilver Edge possui um gatilho micro switch que funciona junto com o chipset SDU ™ para uma resposta quase instantânea do gatilho (tão rápido quanto 0,02 segundos). Quando combinado com um gatilho de golpe curto, os usuários podem atingir uma incrível taxa de tiro semi-automática. Além das peças internas reforçadas, o próprio corpo da GearBox foi bastante reforçado para suportar o estresse de até uma mola M190. Grande reflexão e detalhes foram dedicados a esta GearBox para torná-la mais durável, mais eficiente e, ao mesmo tempo, permanecer compatível com a grande maioria das peças de atualização TOKYO MARUI Spec.', 'https://www.arsenalsports.com/produto/aps-aeg-asr-2e112r2-20-handguard-10-silver-edge-blowback-airsoft-rifle-black-18498.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('APS AEG ASR 2E115X 1.0 THREE GUN CUSTOM SILVER EDGE BLOWBACK AIRSOFT RIFLE RED / BLACK', 'APS', 216, 'https://www.arsenalsports.com/img/18500/produtos/600/b643570ca85e84ea7fbe4e58fcd32252.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'GBB', 'A nova GearBox APS Silver Edge utiliza uma técnica de polimento exclusiva para remover rebarbas e imperfeições superficiais do corpo da GearBox. Este polimento leva a um acabamento incrivelmente liso e uniforme que reduzirá o atrito e diminuirá a carga da caixa de marchas. Essas melhorias levam a uma GearBox mais eficiente que usará menos energia, gerará menos desgaste e permitirá o ciclo mais suave possível para desempenho aprimorado, além de estender muito a vida útil da GearBox.', 'https://www.arsenalsports.com/produto/aps-aeg-asr-2e115x-10-three-gun-custom-silver-edge-blowback-airsoft-rifle-red--black-18500.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('APS AEG ASR 2E116R1 2.0 SILVER EDGE BLOWBACK AIRSOFT RIFLE BLACK', 'APS', 226, 'https://www.arsenalsports.com/img/18504/produtos/600/4f95df42f11b007b5be2c62d3b88709b.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'GBB', 'O sistema Rail adaptado de baixo perfil APS EBB AEG é um Airsoft M4 AEG pré-personalizado com o que há de mais moderno em acessórios e tecnologia. Projetado para ser aerodinâmico e de alta velocidade, este rifle apresenta grande ergonomia, tornando-o muito confortável de manejar. O punho do motor de polímero de uma peça e o Trigger Guard são ergonomicamente projetados para aumentar o conforto do operador e estão equipados com um suporte de eslinga QD ambidestro na parte traseira do punho. O HandGuard frontal possui suportes de montagem Keymod para uso com a maioria dos acessórios Keymod de especificação Airsoft. A nova GearBox APS Silver Edge utiliza uma técnica de polimento exclusiva para remover rebarbas e imperfeições superficiais do corpo da GearBox. Este polimento leva a um acabamento incrivelmente liso e uniforme que reduzirá o atrito e diminuirá a carga da caixa de marchas. Essas melhorias levam a uma GearBox mais eficiente que usará menos energia, gerará menos desgaste e permitirá o ciclo mais suave possível para desempenho aprimorado, além de estender muito a vida útil da GearBox.', 'https://www.arsenalsports.com/produto/aps-aeg-asr-2e116r1-20-silver-edge-blowback-airsoft-rifle-black-18504.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('APS AEG ASR115 SPYDER STYLE KEYMOD AIRSOFT RIFLE BLACK MULTICAM', 'APS', 199, 'https://www.arsenalsports.com/img/11217/produtos/600/3b26f73d9ec39f418c56a73f9402e892.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'AEG', 'Os modelos mais recentes ASR115 da APS são construídos com precisão, durabilidade e qualidade. Essas armas Airsoft de grau de jogo são equipadas com um sistema KeyMod HANDGUARD de 12,5 polegadas e visões laterais de fibra óptica. O longo cano melhora o agrupamento e a precisão. A magazine de polímero é 40% mais leve do que uma magazine metálica tradicional, aumentando a manobrabilidade. O ASR115 também inclui uma caixa de engrenagens de Silver Edge que resulta em uma operação mais suave.', 'https://www.arsenalsports.com/produto/aps-aeg-asr115-spyder-style-keymod-airsoft-rifle-black-multicam-11217.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('APS AEG ASR116 LOW PROFILE ADAPTIVE RAIL AIRSOFT RIFLE MULTICAM', 'APS', 199, 'https://www.arsenalsports.com/img/11219/produtos/600/1cae0d8db07e05dda3da3cd9148edb34.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'AEG', 'O novo ASR116 está agora disponível em dezembro de 2014. Este padrão de pistola vem com um Adaptador HANDGUARD de perfil baixo de 12,5 "usando o sistema KeyMod. O sistema KeyMod destinado a ser usado como método de conexão direta para acessórios como luz de flash, módulos de laser, pontos de vista, escopo, suporte de barricada e muitos outros. Esta arma vem com trilhos 3x MIL-STD 1913, tornando-a mais tática em operação. **Características do ASR116:** New Flip Up Athena Sights (Tudo em uma Pistola e Rifle Sights together) GearBox traseira de sopro elétrico de argola de 8mm Full Bearing Placa Recoil revestida com titânio reforçado Ergonomics Rubber Feel Pistol Grip 6 posições ajustáveis Crane Stock Silver Edge Gear Box.', 'https://www.arsenalsports.com/produto/aps-aeg-asr116-low-profile-adaptive-rail-airsoft-rifle-multicam-11219.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('APS AEG ASR117 BOAR TACTICAL SILVER EDGE KEYMOD AIRSOFT RIFLE BLACK', 'APS', 190, 'https://www.arsenalsports.com/img/10338/produtos/600/dc8a5399120e2702a5d16e0fa59666ca.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'AEG', 'O novo APS Silver Edge Gearbox utiliza uma técnica de polimento exclusiva para remover as rebarbas e as imperfeições da superfície do compartimento da caixa de velocidades. Este polimento leva a um acabamento incrivelmente suave e uniforme que irá reduzir a fricção e baixar a carga da caixa de velocidades. Essas melhorias levam a uma caixa de velocidades mais eficiente que usará menos energia, gerará menos desgaste e permitirá o ciclo mais suave possível para um desempenho melhorado, além de ampliar a vida útil da sua caixa de velocidades.

**Características:**

- Precisão Lipo pronto ciclo alto Silver Edge caixa de velocidades
- Hakkotsu endurance AEG grip do motor
- Receptor de metal completo com marcas gravadas a laser
- Flip-up frente e vista traseira
- Visão frontal de fibra óptica de alta visibilidade
- Estilo de competição de alta velocidade, gatilho plano personalizado
- Trava de alça de carga estendida
- Ambidestro QD um ponto de funda giratória
- Prateleira simulada revestida de ouro
- Parada de bolt de funcionamento para fácil ajuste de espera
- "Yippie kay yay" capa de poeira gravada a laser
- Full metal 14.5 "Keymod rail system
- Compensador agressivo portado
- 3x trilhos acessórios adicionais incluídos
- Estoque de crane retrátil de 6 posições
- Trilho superior de comprimento total', 'https://www.arsenalsports.com/produto/aps-aeg-asr117-boar-tactical-silver-edge-keymod-airsoft-rifle-black-10338.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('APS AEG ASR118 BOAR TACTICAL SILVER EDGE KEYMOD AIRSOFT RIFLE BLACK MULTICAM', 'APS', 210, 'https://www.arsenalsports.com/img/11310/produtos/600/cb2f5229dd90bef9bd9d8eebe350f912.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'AEG', 'O novo APS Silver Edge Gearbox utiliza uma técnica de polimento exclusiva para remover as rebarbas e as imperfeições da superfície do compartimento da caixa de velocidades. Este polimento leva a um acabamento incrivelmente suave e uniforme que irá reduzir a fricção e baixar a carga da caixa de velocidades. Essas melhorias levam a uma caixa de velocidades mais eficiente que usará menos energia, gerará menos desgaste e permitirá o ciclo mais suave possível para um desempenho melhorado, além de ampliar a vida útil da sua caixa de velocidades. Características: - Precisão Lipo pronto ciclo alto Silver Edge caixa de velocidades - Receptor de metal completo com marcas gravadas a laser - Flip-up frente e vista traseira - Visão frontal de fibra óptica de alta visibilidade - Estilo de competição de alta velocidade, gatilho plano personalizado - Trava de alça de carga estendida - magazine ambidextrus e captura de bolt - Aperto de motor com ponta de mão personalizado - Tomada de tom de ouro selecionada, captura de mag e bolt - Ambidestro QD um ponto de funda giratória - Prateleira simulada revestida de ouro - Parada de bolt de funcionamento para fácil ajuste de espera - ''Yippie kay yay'' capa de poeira gravada a laser gravada - Full metal 14.5 ''Keymod rail system - Compensador agressivo portado - 3x trilhos acessórios adicionais incluídos - Estoque de crane retrátil de 6 posições - Trilho superior de comprimento total', 'https://www.arsenalsports.com/produto/aps-aeg-asr118-boar-tactical-silver-edge-keymod-airsoft-rifle-black-multicam-11310.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('APS AEG ASR118 GOLDEN NATION SILVER EDGE AIRSOFT RIFLE BLACK', 'APS', 190, 'https://www.arsenalsports.com/img/10339/produtos/600/2ca0e6fbd0837ac41c00617df49f6d0c.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'AEG', 'O novo APS Silver Edge Gearbox utiliza uma técnica de polimento exclusiva para remover as rebarbas e as imperfeições da superfície do compartimento da caixa de velocidades. Este polimento leva a um acabamento incrivelmente suave e uniforme que irá reduzir a fricção e baixar a carga da caixa de velocidades. Essas melhorias levam a uma caixa de velocidades mais eficiente que usará menos energia, gerará menos desgaste e permitirá o ciclo mais suave possível para um desempenho melhorado, além de ampliar a vida útil da sua caixa de velocidades.', 'https://www.arsenalsports.com/produto/aps-aeg-asr118-golden-nation-silver-edge-airsoft-rifle-black-10339.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('APS AEG ASR120 SILVER EDGE AIRSOFT RIFLE BLACK', 'APS', 240, 'https://www.arsenalsports.com/img/12863/produtos/600/a62cdcbe029a4d584e6be48ac34f320f.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'AEG', 'O FMR (Froged Match Rifle) não é apenas estético: a frente é do tipo Keymod e o sistema é octogonal, isto é, permite também instalar os acessórios K-mod nas 4 posições inclinadas em 45 ° e é fornecido com 3 slides removíveis e reposicionáveis. Mecanicamente, o FMR MOD1 monta a nova GearBox Silver Edge, um sistema mecânico de última geração.', 'https://www.arsenalsports.com/produto/aps-aeg-asr120-silver-edge-airsoft-rifle-black-12863.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('APS AEG ASR122 SILVER EDGE PDW STYLE BLOWBACK AIRSOFT RIFLE BLACK', 'APS', 230, 'https://www.arsenalsports.com/img/14423/produtos/600/63402d9133484a6a62f4d58fad51c2a2.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'GBB', 'The APS AEG ASR122 is the latest AR-15 AEG from APS, featuring a telescoping CRS stock, Sound Blaster Type A sound amplifier, and M-LOK handguard. It provides adjustable hop-up, three firing modes, and a large battery compartment. This model includes a ''Ghost Face'' logo and is designed for intimidating sound and appearance. It has metal components, adjustable sights, and is compatible with 7.4v or 11.1v Li Po batteries.', 'https://www.arsenalsports.com/produto/aps-aeg-asr122-silver-edge-pdw-style-blowback-airsoft-rifle-black-14423.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('APS AEG GHOST PATROL SILVER EDGE M4 WITH SDU 2.0 ECU AIRSOFT RIFLE GREEN PHANTOM', 'APS', 256, 'https://www.arsenalsports.com/img/22249/produtos/600/0f5a94866128287a0c862eb896984e29.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'AEG', 'Receptor inferior de liga de alumínio estilo tarugo usinado em CNC de alta qualidade. Controles de tiro totalmente ambidestros facilitam a manipulação por atiradores destros e canhotos. Nova GearBox eSilverEdge com chipset SDU avançado para gerenciar o consumo de amperagem tiro a tiro (a GearBox puxa apenas 11 amperes a ~ 380 FPS) para melhorar a consistência, desempenho e resposta instantânea do gatilho, tornando esta uma das caixas de engrenagens de estoque mais eficientes do mercado. O novo chip SDU2.0 ECU (Electronic Control Unit) apresenta a capacidade de programar seu gatilho para 5 modos diferentes. Oliver Drab pintado em BB025 Sound Blaster Flash Hider / Outer Barrel / Mag Release / Bolt Release / Trigger / Fire Selector and Charging Handle. HandGuard 10 Javali M-LOK. coronha RS-3 retrátil. Vários pontos de montagem giratórios de eslinga QD. Motorgrip ergonômico em polímero com backstraps intercambiáveis.', 'https://www.arsenalsports.com/produto/aps-aeg-ghost-patrol-silver-edge-m4-with-sdu-20-ecu-airsoft-rifle-green-phantom-22249.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('APS AEG M4 GHOST PATROL EDGE-II AIRSOFT RIFLE DUAL TONE', 'APS', 234, 'https://www.arsenalsports.com/img/28458/produtos/600/00a80efa8d0ac2ad638a17f58a68e903.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'AEG', 'O novo AEG Modelo 125 chegará no primeiro trimestre de 2024. O modelo 125 vem com muitos recursos novos: Protetor de mão M-Lok, coronha retrátil RS-4, adaptador de coronha dobrável, mira Falcon e GearBox Edge II. Com potencia de até 410 FPS e taxa de disparo de 750 ~ 850 tiros por minuto.', 'https://www.arsenalsports.com/produto/aps-aeg-m4-ghost-patrol-edgeii-airsoft-rifle-dual-tone-28458.html', true, 25, 20, 3);
INSERT INTO public.products (name, brand, usd_price, image_url, category_id, system, description, source_url, is_available, tax_importer, tax_admin, tax_nf) VALUES ('APS AEG PHANTOM EXTREMIS MARK I KEYMOD 10.5" BLOWBACK AIRSOFT RIFLE TAN', 'APS', 196, 'https://www.arsenalsports.com/img/12042/produtos/600/9525bdacf1fde9367dd037d0aff138a1.jpg', (SELECT id FROM public.categories WHERE slug = 'rifles'), 'GBB', 'Phantom Extremis Rifle (PER) Extremis é um rifle tático construído para o usuário avançado de airsoft. Sua aparência parece ficção científica, o design do receptor do corpo vem da.idea de uma nave espacial. Colocamos todos os recursos avançados como switches Ambi e botão para os jogadores. À medida que a mola de mudança rápida, a Silver Edge Gear Box é altamente conhecida no mercado, este rifle PER faz pleno uso da função de mudança de mudança rápida que beneficia o usuário. Nós acreditamos firmemente que este rifle dominará o mercado em 2017. É um rifle leve e pontilhado com aspecto cibernético.', 'https://www.arsenalsports.com/produto/aps-aeg-phantom-extremis-mark-i-keymod-105-blowback-airsoft-rifle-tan-12042.html', true, 25, 20, 3);